language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'

script:
  # - npm run lint
  # - npm run test
  # - npm run check-coverage
after_success:
  # - npm run travis-deploy-once "npm run semantic-release"
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
